name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build the file
        run: |
          npm install
          npm run build

      - name: Upload build result to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/xiaomi-vacuum-map-card.js
          asset_name: xiaomi-vacuum-map-card.js
          tag: ${{ github.ref }}
          overwrite: true